import '../styles/globals.scss'
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Stripe Press - Ideas for progress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.webp" />
      </Head>
      <Component {...pageProps} />
    </>
  )  
}

export default MyApp
